using CopaDraft.Engine;

namespace CopaDraft.Engine.Tests;

/// <summary>
/// Asserts the C# Rng matches the JS lib/rng.js bit-for-bit, using golden
/// vectors generated by tools/gen-rng-golden.js (golden/rng.json).
/// </summary>
public class RngParityTests
{
    private static readonly RngGolden G = Golden.Load<RngGolden>("rng.json");

    [Fact]
    public void Next_Matches_Js_For_Multiple_Seeds()
    {
        foreach (NextCase c in G.NextMulti)
        {
            var rng = new Rng(c.Seed);
            for (int i = 0; i < c.Values.Length; i++)
            {
                double actual = rng.Next();
                Assert.True(actual == c.Values[i],
                    $"seed={c.Seed} i={i}: expected {c.Values[i]:R}, got {actual:R}");
            }
        }
    }

    [Fact]
    public void NextInt_Matches_Js()
    {
        foreach (IntCase c in G.Int)
        {
            var rng = new Rng(c.Seed);
            for (int i = 0; i < c.Values.Length; i++)
                Assert.Equal(c.Values[i], rng.NextInt(c.Min, c.Max));
        }
    }

    [Fact]
    public void Pick_Matches_Js()
    {
        foreach (PickCase c in G.Pick)
        {
            var rng = new Rng(c.Seed);
            int[] arr = Enumerable.Range(0, c.N).ToArray();
            for (int i = 0; i < c.Indices.Length; i++)
                Assert.Equal(c.Indices[i], rng.Pick(arr));
        }
    }

    [Fact]
    public void Weighted_Matches_Js()
    {
        foreach (WeightedCase c in G.Weighted)
        {
            var rng = new Rng(c.Seed);
            var items = c.Weights.Select((w, i) => (Item: i, W: w)).ToArray();
            for (int i = 0; i < c.Picks.Length; i++)
                Assert.Equal(c.Picks[i], rng.Weighted(items));
        }
    }

    [Fact]
    public void SeedFrom_Matches_Js()
    {
        foreach (SeedFromCase c in G.SeedFrom)
            Assert.Equal(c.H, Rng.SeedFrom(c.S));
    }
}

// ---- golden DTOs (match the JSON shape from tools/gen-rng-golden.js) ----
public sealed record RngGolden(
    NextCase[] NextMulti,
    IntCase[] Int,
    PickCase[] Pick,
    WeightedCase[] Weighted,
    SeedFromCase[] SeedFrom);

public sealed record NextCase(uint Seed, double[] Values);
public sealed record IntCase(uint Seed, int Min, int Max, int[] Values);
public sealed record PickCase(uint Seed, int N, int Count, int[] Indices);
public sealed record WeightedCase(uint Seed, double[] Weights, int Count, int[] Picks);
public sealed record SeedFromCase(string S, uint H);
